package org.laidu.learn.mybatis.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AppUserExample {
    protected String orderByClause;

    protected boolean distinct;

    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer offset;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    protected Integer rows;

    public AppUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    public String getOrderByClause() {
        return orderByClause;
    }

    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    public boolean isDistinct() {
        return distinct;
    }

    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        rows = null;
        offset = null;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getOffset() {
        return this.offset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public void setRows(Integer rows) {
        this.rows = rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public Integer getRows() {
        return this.rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AppUserExample limit(Integer rows) {
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AppUserExample limit(Integer offset, Integer rows) {
        this.offset = offset;
        this.rows = rows;
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ca_app_user
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public AppUserExample page(Integer page, Integer pageSize) {
        this.offset = page * pageSize;
        this.rows = pageSize;
        return this;
    }

    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNull() {
            addCriterion("open_id is null");
            return (Criteria) this;
        }

        public Criteria andOpenIdIsNotNull() {
            addCriterion("open_id is not null");
            return (Criteria) this;
        }

        public Criteria andOpenIdEqualTo(String value) {
            addCriterion("open_id =", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotEqualTo(String value) {
            addCriterion("open_id <>", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThan(String value) {
            addCriterion("open_id >", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdGreaterThanOrEqualTo(String value) {
            addCriterion("open_id >=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThan(String value) {
            addCriterion("open_id <", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLessThanOrEqualTo(String value) {
            addCriterion("open_id <=", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdLike(String value) {
            addCriterion("open_id like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotLike(String value) {
            addCriterion("open_id not like", value, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdIn(List<String> values) {
            addCriterion("open_id in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotIn(List<String> values) {
            addCriterion("open_id not in", values, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdBetween(String value1, String value2) {
            addCriterion("open_id between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andOpenIdNotBetween(String value1, String value2) {
            addCriterion("open_id not between", value1, value2, "openId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIsNull() {
            addCriterion("register_channel is null");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIsNotNull() {
            addCriterion("register_channel is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelEqualTo(Long value) {
            addCriterion("register_channel =", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelNotEqualTo(Long value) {
            addCriterion("register_channel <>", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelGreaterThan(Long value) {
            addCriterion("register_channel >", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelGreaterThanOrEqualTo(Long value) {
            addCriterion("register_channel >=", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelLessThan(Long value) {
            addCriterion("register_channel <", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelLessThanOrEqualTo(Long value) {
            addCriterion("register_channel <=", value, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIn(List<Long> values) {
            addCriterion("register_channel in", values, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelNotIn(List<Long> values) {
            addCriterion("register_channel not in", values, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelBetween(Long value1, Long value2) {
            addCriterion("register_channel between", value1, value2, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelNotBetween(Long value1, Long value2) {
            addCriterion("register_channel not between", value1, value2, "registerChannel");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andIdCardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardEqualTo(String value) {
            addCriterion("id_card =", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThan(String value) {
            addCriterion("id_card >", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThan(String value) {
            addCriterion("id_card <", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardLike(String value) {
            addCriterion("id_card like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotLike(String value) {
            addCriterion("id_card not like", value, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardIn(List<String> values) {
            addCriterion("id_card in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andIdCardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "idCard");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressIsNull() {
            addCriterion("id_card_detail_address is null");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressIsNotNull() {
            addCriterion("id_card_detail_address is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressEqualTo(String value) {
            addCriterion("id_card_detail_address =", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressNotEqualTo(String value) {
            addCriterion("id_card_detail_address <>", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressGreaterThan(String value) {
            addCriterion("id_card_detail_address >", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressGreaterThanOrEqualTo(String value) {
            addCriterion("id_card_detail_address >=", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressLessThan(String value) {
            addCriterion("id_card_detail_address <", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressLessThanOrEqualTo(String value) {
            addCriterion("id_card_detail_address <=", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressLike(String value) {
            addCriterion("id_card_detail_address like", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressNotLike(String value) {
            addCriterion("id_card_detail_address not like", value, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressIn(List<String> values) {
            addCriterion("id_card_detail_address in", values, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressNotIn(List<String> values) {
            addCriterion("id_card_detail_address not in", values, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressBetween(String value1, String value2) {
            addCriterion("id_card_detail_address between", value1, value2, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIdCardDetailAddressNotBetween(String value1, String value2) {
            addCriterion("id_card_detail_address not between", value1, value2, "idCardDetailAddress");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardIsNull() {
            addCriterion("is_verify_id_card is null");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardIsNotNull() {
            addCriterion("is_verify_id_card is not null");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardEqualTo(Boolean value) {
            addCriterion("is_verify_id_card =", value, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardNotEqualTo(Boolean value) {
            addCriterion("is_verify_id_card <>", value, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardGreaterThan(Boolean value) {
            addCriterion("is_verify_id_card >", value, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_verify_id_card >=", value, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardLessThan(Boolean value) {
            addCriterion("is_verify_id_card <", value, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardLessThanOrEqualTo(Boolean value) {
            addCriterion("is_verify_id_card <=", value, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardIn(List<Boolean> values) {
            addCriterion("is_verify_id_card in", values, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardNotIn(List<Boolean> values) {
            addCriterion("is_verify_id_card not in", values, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardBetween(Boolean value1, Boolean value2) {
            addCriterion("is_verify_id_card between", value1, value2, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIsVerifyIdCardNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_verify_id_card not between", value1, value2, "isVerifyIdCard");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupIsNull() {
            addCriterion("id_card_coverup is null");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupIsNotNull() {
            addCriterion("id_card_coverup is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupEqualTo(String value) {
            addCriterion("id_card_coverup =", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupNotEqualTo(String value) {
            addCriterion("id_card_coverup <>", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupGreaterThan(String value) {
            addCriterion("id_card_coverup >", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupGreaterThanOrEqualTo(String value) {
            addCriterion("id_card_coverup >=", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupLessThan(String value) {
            addCriterion("id_card_coverup <", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupLessThanOrEqualTo(String value) {
            addCriterion("id_card_coverup <=", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupLike(String value) {
            addCriterion("id_card_coverup like", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupNotLike(String value) {
            addCriterion("id_card_coverup not like", value, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupIn(List<String> values) {
            addCriterion("id_card_coverup in", values, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupNotIn(List<String> values) {
            addCriterion("id_card_coverup not in", values, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupBetween(String value1, String value2) {
            addCriterion("id_card_coverup between", value1, value2, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverupNotBetween(String value1, String value2) {
            addCriterion("id_card_coverup not between", value1, value2, "idCardCoverup");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownIsNull() {
            addCriterion("id_card_coverdown is null");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownIsNotNull() {
            addCriterion("id_card_coverdown is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownEqualTo(String value) {
            addCriterion("id_card_coverdown =", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownNotEqualTo(String value) {
            addCriterion("id_card_coverdown <>", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownGreaterThan(String value) {
            addCriterion("id_card_coverdown >", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownGreaterThanOrEqualTo(String value) {
            addCriterion("id_card_coverdown >=", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownLessThan(String value) {
            addCriterion("id_card_coverdown <", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownLessThanOrEqualTo(String value) {
            addCriterion("id_card_coverdown <=", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownLike(String value) {
            addCriterion("id_card_coverdown like", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownNotLike(String value) {
            addCriterion("id_card_coverdown not like", value, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownIn(List<String> values) {
            addCriterion("id_card_coverdown in", values, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownNotIn(List<String> values) {
            addCriterion("id_card_coverdown not in", values, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownBetween(String value1, String value2) {
            addCriterion("id_card_coverdown between", value1, value2, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardCoverdownNotBetween(String value1, String value2) {
            addCriterion("id_card_coverdown not between", value1, value2, "idCardCoverdown");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldIsNull() {
            addCriterion("id_card_hold is null");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldIsNotNull() {
            addCriterion("id_card_hold is not null");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldEqualTo(String value) {
            addCriterion("id_card_hold =", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldNotEqualTo(String value) {
            addCriterion("id_card_hold <>", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldGreaterThan(String value) {
            addCriterion("id_card_hold >", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldGreaterThanOrEqualTo(String value) {
            addCriterion("id_card_hold >=", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldLessThan(String value) {
            addCriterion("id_card_hold <", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldLessThanOrEqualTo(String value) {
            addCriterion("id_card_hold <=", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldLike(String value) {
            addCriterion("id_card_hold like", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldNotLike(String value) {
            addCriterion("id_card_hold not like", value, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldIn(List<String> values) {
            addCriterion("id_card_hold in", values, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldNotIn(List<String> values) {
            addCriterion("id_card_hold not in", values, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldBetween(String value1, String value2) {
            addCriterion("id_card_hold between", value1, value2, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIdCardHoldNotBetween(String value1, String value2) {
            addCriterion("id_card_hold not between", value1, value2, "idCardHold");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthIsNull() {
            addCriterion("is_other_picture_auth is null");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthIsNotNull() {
            addCriterion("is_other_picture_auth is not null");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthEqualTo(Boolean value) {
            addCriterion("is_other_picture_auth =", value, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthNotEqualTo(Boolean value) {
            addCriterion("is_other_picture_auth <>", value, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthGreaterThan(Boolean value) {
            addCriterion("is_other_picture_auth >", value, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_other_picture_auth >=", value, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthLessThan(Boolean value) {
            addCriterion("is_other_picture_auth <", value, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthLessThanOrEqualTo(Boolean value) {
            addCriterion("is_other_picture_auth <=", value, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthIn(List<Boolean> values) {
            addCriterion("is_other_picture_auth in", values, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthNotIn(List<Boolean> values) {
            addCriterion("is_other_picture_auth not in", values, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthBetween(Boolean value1, Boolean value2) {
            addCriterion("is_other_picture_auth between", value1, value2, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsOtherPictureAuthNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_other_picture_auth not between", value1, value2, "isOtherPictureAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthIsNull() {
            addCriterion("is_bankcard_auth is null");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthIsNotNull() {
            addCriterion("is_bankcard_auth is not null");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthEqualTo(Boolean value) {
            addCriterion("is_bankcard_auth =", value, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthNotEqualTo(Boolean value) {
            addCriterion("is_bankcard_auth <>", value, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthGreaterThan(Boolean value) {
            addCriterion("is_bankcard_auth >", value, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_bankcard_auth >=", value, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthLessThan(Boolean value) {
            addCriterion("is_bankcard_auth <", value, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthLessThanOrEqualTo(Boolean value) {
            addCriterion("is_bankcard_auth <=", value, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthIn(List<Boolean> values) {
            addCriterion("is_bankcard_auth in", values, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthNotIn(List<Boolean> values) {
            addCriterion("is_bankcard_auth not in", values, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthBetween(Boolean value1, Boolean value2) {
            addCriterion("is_bankcard_auth between", value1, value2, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andIsBankcardAuthNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_bankcard_auth not between", value1, value2, "isBankcardAuth");
            return (Criteria) this;
        }

        public Criteria andSignaturePicIsNull() {
            addCriterion("signature_pic is null");
            return (Criteria) this;
        }

        public Criteria andSignaturePicIsNotNull() {
            addCriterion("signature_pic is not null");
            return (Criteria) this;
        }

        public Criteria andSignaturePicEqualTo(String value) {
            addCriterion("signature_pic =", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicNotEqualTo(String value) {
            addCriterion("signature_pic <>", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicGreaterThan(String value) {
            addCriterion("signature_pic >", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicGreaterThanOrEqualTo(String value) {
            addCriterion("signature_pic >=", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicLessThan(String value) {
            addCriterion("signature_pic <", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicLessThanOrEqualTo(String value) {
            addCriterion("signature_pic <=", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicLike(String value) {
            addCriterion("signature_pic like", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicNotLike(String value) {
            addCriterion("signature_pic not like", value, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicIn(List<String> values) {
            addCriterion("signature_pic in", values, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicNotIn(List<String> values) {
            addCriterion("signature_pic not in", values, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicBetween(String value1, String value2) {
            addCriterion("signature_pic between", value1, value2, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andSignaturePicNotBetween(String value1, String value2) {
            addCriterion("signature_pic not between", value1, value2, "signaturePic");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthIsNull() {
            addCriterion("is_additional_auth is null");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthIsNotNull() {
            addCriterion("is_additional_auth is not null");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthEqualTo(Boolean value) {
            addCriterion("is_additional_auth =", value, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthNotEqualTo(Boolean value) {
            addCriterion("is_additional_auth <>", value, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthGreaterThan(Boolean value) {
            addCriterion("is_additional_auth >", value, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_additional_auth >=", value, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthLessThan(Boolean value) {
            addCriterion("is_additional_auth <", value, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthLessThanOrEqualTo(Boolean value) {
            addCriterion("is_additional_auth <=", value, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthIn(List<Boolean> values) {
            addCriterion("is_additional_auth in", values, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthNotIn(List<Boolean> values) {
            addCriterion("is_additional_auth not in", values, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthBetween(Boolean value1, Boolean value2) {
            addCriterion("is_additional_auth between", value1, value2, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsAdditionalAuthNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_additional_auth not between", value1, value2, "isAdditionalAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthIsNull() {
            addCriterion("is_emergency_auth is null");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthIsNotNull() {
            addCriterion("is_emergency_auth is not null");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthEqualTo(Boolean value) {
            addCriterion("is_emergency_auth =", value, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthNotEqualTo(Boolean value) {
            addCriterion("is_emergency_auth <>", value, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthGreaterThan(Boolean value) {
            addCriterion("is_emergency_auth >", value, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_emergency_auth >=", value, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthLessThan(Boolean value) {
            addCriterion("is_emergency_auth <", value, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthLessThanOrEqualTo(Boolean value) {
            addCriterion("is_emergency_auth <=", value, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthIn(List<Boolean> values) {
            addCriterion("is_emergency_auth in", values, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthNotIn(List<Boolean> values) {
            addCriterion("is_emergency_auth not in", values, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthBetween(Boolean value1, Boolean value2) {
            addCriterion("is_emergency_auth between", value1, value2, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andIsEmergencyAuthNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_emergency_auth not between", value1, value2, "isEmergencyAuth");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNull() {
            addCriterion("user_status is null");
            return (Criteria) this;
        }

        public Criteria andUserStatusIsNotNull() {
            addCriterion("user_status is not null");
            return (Criteria) this;
        }

        public Criteria andUserStatusEqualTo(Integer value) {
            addCriterion("user_status =", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotEqualTo(Integer value) {
            addCriterion("user_status <>", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThan(Integer value) {
            addCriterion("user_status >", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_status >=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThan(Integer value) {
            addCriterion("user_status <", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusLessThanOrEqualTo(Integer value) {
            addCriterion("user_status <=", value, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusIn(List<Integer> values) {
            addCriterion("user_status in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotIn(List<Integer> values) {
            addCriterion("user_status not in", values, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusBetween(Integer value1, Integer value2) {
            addCriterion("user_status between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andUserStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("user_status not between", value1, value2, "userStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andBlackStatusIsNull() {
            addCriterion("black_status is null");
            return (Criteria) this;
        }

        public Criteria andBlackStatusIsNotNull() {
            addCriterion("black_status is not null");
            return (Criteria) this;
        }

        public Criteria andBlackStatusEqualTo(Integer value) {
            addCriterion("black_status =", value, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusNotEqualTo(Integer value) {
            addCriterion("black_status <>", value, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusGreaterThan(Integer value) {
            addCriterion("black_status >", value, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("black_status >=", value, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusLessThan(Integer value) {
            addCriterion("black_status <", value, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusLessThanOrEqualTo(Integer value) {
            addCriterion("black_status <=", value, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusIn(List<Integer> values) {
            addCriterion("black_status in", values, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusNotIn(List<Integer> values) {
            addCriterion("black_status not in", values, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusBetween(Integer value1, Integer value2) {
            addCriterion("black_status between", value1, value2, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andBlackStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("black_status not between", value1, value2, "blackStatus");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNull() {
            addCriterion("audit_time is null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIsNotNull() {
            addCriterion("audit_time is not null");
            return (Criteria) this;
        }

        public Criteria andAuditTimeEqualTo(Date value) {
            addCriterion("audit_time =", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotEqualTo(Date value) {
            addCriterion("audit_time <>", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThan(Date value) {
            addCriterion("audit_time >", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audit_time >=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThan(Date value) {
            addCriterion("audit_time <", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeLessThanOrEqualTo(Date value) {
            addCriterion("audit_time <=", value, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeIn(List<Date> values) {
            addCriterion("audit_time in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotIn(List<Date> values) {
            addCriterion("audit_time not in", values, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeBetween(Date value1, Date value2) {
            addCriterion("audit_time between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andAuditTimeNotBetween(Date value1, Date value2) {
            addCriterion("audit_time not between", value1, value2, "auditTime");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusIsNull() {
            addCriterion("cash_black_status is null");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusIsNotNull() {
            addCriterion("cash_black_status is not null");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusEqualTo(Integer value) {
            addCriterion("cash_black_status =", value, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusNotEqualTo(Integer value) {
            addCriterion("cash_black_status <>", value, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusGreaterThan(Integer value) {
            addCriterion("cash_black_status >", value, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("cash_black_status >=", value, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusLessThan(Integer value) {
            addCriterion("cash_black_status <", value, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusLessThanOrEqualTo(Integer value) {
            addCriterion("cash_black_status <=", value, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusIn(List<Integer> values) {
            addCriterion("cash_black_status in", values, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusNotIn(List<Integer> values) {
            addCriterion("cash_black_status not in", values, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusBetween(Integer value1, Integer value2) {
            addCriterion("cash_black_status between", value1, value2, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashBlackStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("cash_black_status not between", value1, value2, "cashBlackStatus");
            return (Criteria) this;
        }

        public Criteria andCashQuotaIsNull() {
            addCriterion("cash_quota is null");
            return (Criteria) this;
        }

        public Criteria andCashQuotaIsNotNull() {
            addCriterion("cash_quota is not null");
            return (Criteria) this;
        }

        public Criteria andCashQuotaEqualTo(BigDecimal value) {
            addCriterion("cash_quota =", value, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaNotEqualTo(BigDecimal value) {
            addCriterion("cash_quota <>", value, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaGreaterThan(BigDecimal value) {
            addCriterion("cash_quota >", value, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_quota >=", value, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaLessThan(BigDecimal value) {
            addCriterion("cash_quota <", value, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_quota <=", value, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaIn(List<BigDecimal> values) {
            addCriterion("cash_quota in", values, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaNotIn(List<BigDecimal> values) {
            addCriterion("cash_quota not in", values, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_quota between", value1, value2, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andCashQuotaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_quota not between", value1, value2, "cashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaIsNull() {
            addCriterion("frozen_cash_quota is null");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaIsNotNull() {
            addCriterion("frozen_cash_quota is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaEqualTo(BigDecimal value) {
            addCriterion("frozen_cash_quota =", value, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaNotEqualTo(BigDecimal value) {
            addCriterion("frozen_cash_quota <>", value, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaGreaterThan(BigDecimal value) {
            addCriterion("frozen_cash_quota >", value, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_cash_quota >=", value, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaLessThan(BigDecimal value) {
            addCriterion("frozen_cash_quota <", value, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_cash_quota <=", value, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaIn(List<BigDecimal> values) {
            addCriterion("frozen_cash_quota in", values, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaNotIn(List<BigDecimal> values) {
            addCriterion("frozen_cash_quota not in", values, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_cash_quota between", value1, value2, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCashQuotaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_cash_quota not between", value1, value2, "frozenCashQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaIsNull() {
            addCriterion("credit_quota is null");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaIsNotNull() {
            addCriterion("credit_quota is not null");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaEqualTo(BigDecimal value) {
            addCriterion("credit_quota =", value, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaNotEqualTo(BigDecimal value) {
            addCriterion("credit_quota <>", value, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaGreaterThan(BigDecimal value) {
            addCriterion("credit_quota >", value, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("credit_quota >=", value, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaLessThan(BigDecimal value) {
            addCriterion("credit_quota <", value, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("credit_quota <=", value, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaIn(List<BigDecimal> values) {
            addCriterion("credit_quota in", values, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaNotIn(List<BigDecimal> values) {
            addCriterion("credit_quota not in", values, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("credit_quota between", value1, value2, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andCreditQuotaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("credit_quota not between", value1, value2, "creditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaIsNull() {
            addCriterion("frozen_credit_quota is null");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaIsNotNull() {
            addCriterion("frozen_credit_quota is not null");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaEqualTo(BigDecimal value) {
            addCriterion("frozen_credit_quota =", value, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaNotEqualTo(BigDecimal value) {
            addCriterion("frozen_credit_quota <>", value, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaGreaterThan(BigDecimal value) {
            addCriterion("frozen_credit_quota >", value, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_credit_quota >=", value, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaLessThan(BigDecimal value) {
            addCriterion("frozen_credit_quota <", value, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("frozen_credit_quota <=", value, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaIn(List<BigDecimal> values) {
            addCriterion("frozen_credit_quota in", values, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaNotIn(List<BigDecimal> values) {
            addCriterion("frozen_credit_quota not in", values, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_credit_quota between", value1, value2, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andFrozenCreditQuotaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("frozen_credit_quota not between", value1, value2, "frozenCreditQuota");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Integer value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Integer value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Integer value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Integer value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Integer> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Integer> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }
    }

    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}