/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class org_laidu_learn_advance_jni_demo_NativeHelloWorld */

#ifndef _Included_org_laidu_learn_advance_jni_demo_NativeHelloWorld
#define _Included_org_laidu_learn_advance_jni_demo_NativeHelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_laidu_learn_advance_jni_demo_NativeHelloWorld
 * Method:    hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_laidu_learn_advance_jni_demo_NativeHelloWorld_hello
  (JNIEnv * , jobject);

#ifdef __cplusplus
}
#endif
#endif
