# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="laidu823@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080

# using beijing timezone
RUN echo "Asia/Shanghai" > /etc/timezone

# The application's jar file
ARG JAR_FILE=target/spring-boot-app-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
ADD ${JAR_FILE} spring-boot-app-0.0.1-SNAPSHOT.jar

# Run the jar file
ENTRYPOINT ["java","-Dfile.encoding=UTF-8","-jar","spring-boot-app-0.0.1-SNAPSHOT.jar"]